from pyscript.Model.data_level.text import Text
from pyscript.Model.data_level.word import Word
from pyscript.Model.data_level.phrase import Phrase
from pyscript.Model.data_level.pos import Pos
from pyscript.Model.data_level.ner import Ner
from pyscript.Model.data_level.spo import Spo
from pyscript.Model.data_level.dep import Dep
from pyscript.Model.data_level.coref import CoRef
from pyscript.Model.data_level.rel import Rel
